### Creating tensors from random samples

In [1]:
import torch

In [2]:
#@title torch.rand() selects random values from a uniform distribution on the interval [0-1]
torch.manual_seed(111)
torch.rand(3, 3)

tensor([[0.7156, 0.9140, 0.2819],
        [0.2581, 0.6311, 0.6001],
        [0.9312, 0.2153, 0.6033]])

In [3]:
#@title torch.rand() selects random values from a standard normal distribution

torch.rand(4,4)

tensor([[0.7328, 0.1857, 0.5101, 0.7545],
        [0.2884, 0.5775, 0.0358, 0.1026],
        [0.3419, 0.4400, 0.6341, 0.6224],
        [0.6334, 0.8580, 0.1572, 0.7853]])

In [4]:
#@title torch.randint() selects random integers generated uniformly between specified low and high values

torch.randint(-1, 10, (3, 3))

tensor([[1, 0, 1],
        [5, 3, 1],
        [6, 7, 6]])